// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Training.EFCore.Context;

#nullable disable

namespace Training.EFCore.Migrations
{
    [DbContext(typeof(SqlContext))]
    partial class SqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Training.Domain.Entity.Drug_Management.Drug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Drug_Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Drug_Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Drug_IsPrescription")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Drug_IsShelves")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Drug_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Drug_Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Drug_Specification")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Drug_Stock")
                        .HasColumnType("int");

                    b.Property<int>("Drug_Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Drug");
                });

            modelBuilder.Entity("Training.Domain.Entity.Drug_Management.Drug_Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Drug_Type_Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Drug_Type_IsShelves")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Drug_Type_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Drug_Type_Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Drug_Type");
                });

            modelBuilder.Entity("Training.Domain.Entity.Drug_Management.Logistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("logistics_company_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Logistics");
                });

            modelBuilder.Entity("Training.Domain.Entity.Drug_Management.Orderdetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("delivery_fee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("drug_number")
                        .HasColumnType("int");

                    b.Property<int>("logistics_company")
                        .HasColumnType("int");

                    b.Property<string>("logistics_number")
                        .HasColumnType("longtext");

                    b.Property<int>("order_status")
                        .HasColumnType("int");

                    b.Property<DateTime>("order_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("payment_code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("payment_number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DrugId");

                    b.HasIndex("UserId");

                    b.ToTable("Orderdetail");
                });

            modelBuilder.Entity("Training.Domain.Entity.Seckill.goods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GoodsImg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GoodsName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("GoodsNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("GoodsPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("goods");
                });

            modelBuilder.Entity("Training.Domain.Entity.Seckill.seckill_Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ActivityStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SeckillNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("SeckillPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("seckill_Activity");
                });

            modelBuilder.Entity("Training.Domain.Entity.Seckill.Seckill_Goods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GoodsId")
                        .HasColumnType("int");

                    b.Property<int>("SeckillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Seckill_Goods");
                });

<<<<<<< HEAD
            modelBuilder.Entity("Training.Domain.Entity.Seckill.SeckillOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Gid")
                        .HasColumnType("int");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrderState")
                        .HasColumnType("int");

                    b.Property<decimal?>("PayMoney")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("PayTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SAId")
                        .HasColumnType("int");

                    b.Property<int>("Uid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SeckillOrder");
                });

=======
>>>>>>> 7c15e5adcce266222ab5ca86412c2d67cb28f0d3
            modelBuilder.Entity("Training.Domain.Entity.UserEntity.Clinical_Reception", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Did")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Uid")
                        .HasColumnType("int");

                    b.Property<int>("UserAge")
                        .HasColumnType("int");

                    b.Property<int>("UserSex")
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .HasColumnType("longtext");

                    b.Property<string>("phone")
                        .HasColumnType("longtext");

                    b.Property<bool>("state")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Clinical_Reception");
                });

            modelBuilder.Entity("Training.Domain.Entity.UserEntity.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("account")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("Training.Domain.Entity.UserEntity.Doctor_label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Did")
                        .HasColumnType("int");

                    b.Property<int>("Lid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Doctor_label");
                });

            modelBuilder.Entity("Training.Domain.Entity.UserEntity.DrugOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Drug_Id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Drug_Number")
                        .HasColumnType("int");

                    b.Property<int>("OrderState")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("drug_img")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("drug_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("drug_price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("inquiry_result_Id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DrugOrder");
                });

            modelBuilder.Entity("Training.Domain.Entity.UserEntity.Inquiry_Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Drug_Id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Drug_Number")
                        .HasColumnType("int");

                    b.Property<string>("drug_img")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("drug_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("drug_price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("inquiry_result_Id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Inquiry_Prescription");
                });

            modelBuilder.Entity("Training.Domain.Entity.UserEntity.Inquiry_Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cid")
                        .HasColumnType("int");

                    b.Property<string>("Drug_method")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("action_in_chief")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("inquiry_result_content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("prescription_Id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Inquiry_Result");
                });

            modelBuilder.Entity("Training.Domain.Entity.UserEntity.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LabelName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("introduce")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Label");
                });

            modelBuilder.Entity("Training.Domain.Entity.UserEntity.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("UserAge")
                        .HasColumnType("int");

                    b.Property<int>("UserSex")
                        .HasColumnType("int");

                    b.Property<string>("account")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("address")
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("phone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Training.Domain.Entity.Drug_Management.Orderdetail", b =>
                {
                    b.HasOne("Training.Domain.Entity.Drug_Management.Drug", "Drug")
                        .WithMany()
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Training.Domain.Entity.UserEntity.User.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Training.Domain.Entity.UserEntity.DrugOrder", b =>
                {
                    b.HasOne("Training.Domain.Entity.UserEntity.User.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
